name: Run script every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries
        run: |
          pip install yfinance
          pip install pandas
          npm uninstall d3.js
      - name: Run script
        run: python stock.py
